TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devkeithley6221.db
DB += devkeithley6221.proto

# DB_INSTALLS += DB

#=======================================
include $(TOP)/configure/RULES
